# -*- perl -*-
use strict;
use warnings;
use tests::tests;
use tests::random;
check_expected (IGNORE_EXIT_CODES => 1, [<<'EOF']);
(write-cache) begin
(write-cache) create "garbage"
(write-cache) open "garbage"
(write-cache) write 0 "garbage"
(write-cache) write 1 "garbage"
(write-cache) write 2 "garbage"
(write-cache) write 3 "garbage"
(write-cache) write 4 "garbage"
(write-cache) write 5 "garbage"
(write-cache) write 6 "garbage"
(write-cache) write 7 "garbage"
(write-cache) write 8 "garbage"
(write-cache) write 9 "garbage"
(write-cache) write 10 "garbage"
(write-cache) write 11 "garbage"
(write-cache) write 12 "garbage"
(write-cache) write 13 "garbage"
(write-cache) write 14 "garbage"
(write-cache) write 15 "garbage"
(write-cache) write 16 "garbage"
(write-cache) write 17 "garbage"
(write-cache) write 18 "garbage"
(write-cache) write 19 "garbage"
(write-cache) write 20 "garbage"
(write-cache) write 21 "garbage"
(write-cache) write 22 "garbage"
(write-cache) write 23 "garbage"
(write-cache) write 24 "garbage"
(write-cache) write 25 "garbage"
(write-cache) write 26 "garbage"
(write-cache) write 27 "garbage"
(write-cache) write 28 "garbage"
(write-cache) write 29 "garbage"
(write-cache) write 30 "garbage"
(write-cache) write 31 "garbage"
(write-cache) write 32 "garbage"
(write-cache) write 33 "garbage"
(write-cache) write 34 "garbage"
(write-cache) write 35 "garbage"
(write-cache) write 36 "garbage"
(write-cache) write 37 "garbage"
(write-cache) write 38 "garbage"
(write-cache) write 39 "garbage"
(write-cache) write 40 "garbage"
(write-cache) write 41 "garbage"
(write-cache) write 42 "garbage"
(write-cache) write 43 "garbage"
(write-cache) write 44 "garbage"
(write-cache) write 45 "garbage"
(write-cache) write 46 "garbage"
(write-cache) write 47 "garbage"
(write-cache) write 48 "garbage"
(write-cache) write 49 "garbage"
(write-cache) write 50 "garbage"
(write-cache) write 51 "garbage"
(write-cache) write 52 "garbage"
(write-cache) write 53 "garbage"
(write-cache) write 54 "garbage"
(write-cache) write 55 "garbage"
(write-cache) write 56 "garbage"
(write-cache) write 57 "garbage"
(write-cache) write 58 "garbage"
(write-cache) write 59 "garbage"
(write-cache) write 60 "garbage"
(write-cache) write 61 "garbage"
(write-cache) write 62 "garbage"
(write-cache) write 63 "garbage"
(write-cache) write 64 "garbage"
(write-cache) write 65 "garbage"
(write-cache) write 66 "garbage"
(write-cache) write 67 "garbage"
(write-cache) write 68 "garbage"
(write-cache) write 69 "garbage"
(write-cache) write 70 "garbage"
(write-cache) write 71 "garbage"
(write-cache) write 72 "garbage"
(write-cache) write 73 "garbage"
(write-cache) write 74 "garbage"
(write-cache) write 75 "garbage"
(write-cache) write 76 "garbage"
(write-cache) write 77 "garbage"
(write-cache) write 78 "garbage"
(write-cache) write 79 "garbage"
(write-cache) write 80 "garbage"
(write-cache) write 81 "garbage"
(write-cache) write 82 "garbage"
(write-cache) write 83 "garbage"
(write-cache) write 84 "garbage"
(write-cache) write 85 "garbage"
(write-cache) write 86 "garbage"
(write-cache) write 87 "garbage"
(write-cache) write 88 "garbage"
(write-cache) write 89 "garbage"
(write-cache) write 90 "garbage"
(write-cache) write 91 "garbage"
(write-cache) write 92 "garbage"
(write-cache) write 93 "garbage"
(write-cache) write 94 "garbage"
(write-cache) write 95 "garbage"
(write-cache) write 96 "garbage"
(write-cache) write 97 "garbage"
(write-cache) write 98 "garbage"
(write-cache) write 99 "garbage"
(write-cache) disk count
(write-cache) write count ok
(write-cache) read count ok
(write-cache) end
EOF
pass;
